### ISSUE TITLE
small difference is ignored and automatically accepted

### ISSUE THREAD

**Issue by FinKingma** [xebia/VisualReview#74] opened 2016-07-22 11:43 UTC
While working on my anti aliasing feature, I've run a few tests and discovered that with a pixel difference of 33 and below, the new image is automatically saved as new baseline.

I started working on my own forked branch with some additional logging and wrote a test for this scenario. However, if any of the contributors has time to help out, please let me know. My closure is still a bit limited.

**Comment by skwakman** [comment] 2016-07-22 11:50
I'm mostly away-from-keyboard until next week, I'll look into it then.

**Comment by FinKingma** [comment] 2016-07-22 12:37
Ok great. So far I've managed to solve it with a dirty fix:
https://github.com/xebia/VisualReview/compare/master...FinKingma:smallDiffBug

The issue lies in the following scenario:

> Given the image contains 686080 pixels
> When an image is uploaded with 33 pixel difference
> Then the percentage difference is 0,004809934701  <- Fail: percentage gets rounded to 0%

In DiffReport.java I still get the value 0,004809934701. But interpreted by clojure, this becomes 0%.
My dirty fix looks for values between 0% and 0.1% and saves them as 0.1%.

**Comment by skwakman** [comment] 2016-07-22 14:18
The loss of double-precision could be caused by the database table format in which the data is stored. It lists the percentage field as `NUMERIC(5, 2)`, which limits the percentage's precision to `xxx.xx` .

Question remains if we really need a higher percentage-precision. Is the user better informed if the percentage is 0.01 or 0.001 ? Or should the system just round it up to the lowest amount, just as your current fix does. I'm leaning towards the latter.

So how to fix this.. I agree the current implementation being confusing and error-prone. The PixelComparator API defines a percentage in the form of a `double`, so we'd expect a `double` to be stored and retrieved. Perhaps we could change the percentage value type of PixelComparator API to something more specific, maybe even a limited-precision BigDecimal of some sorts..? This way, other developers won't get into this same confusion. I'll look into some options next week.

**Comment by skwakman** [comment] 2016-07-28 14:21
@FinKingma I've added a small bit of javadoc in `DiffReport` on master which explains how the percentage field should be filled in terms of rounding and precision. Could you create a PR for your bugfix?

**Comment by FinKingma** [comment] 2016-07-29 07:58
Hm I can't seem to find the javadoc. Added a PR with my fix.

**Comment by skwakman** [comment] 2016-07-30 17:06
ah my bad, forgot to push the commit. It's on master now. Closing this issue as fixed

**Closed by skwakman** 2016-07-30 17:06 UTC
